### ISSUE TITLE
[Feature] 프론트 요구사항

### ISSUE THREAD

**Issue by moonjin-kim** [PlanIt-Project/back-end#108]
### 요약
프로그램 만료/ 취소 등 진행중이지 않은 프로그램도 조회
단일 프로그램 상세 조회

### TODO 리스트
- [x] 프로그램 만료/ 취소 등 진행중이지 않은 프로그램도 조회
- [x] [단일 프로그램 상세 조회
- [x] 특정 트레이너로 예약 조회시 해당 날짜만 검색되도록 수정

### 상세 설명
[여기에 기능 요청의 자세한 설명을 작성하세요.]

### ETC
[그 외의 사항을 작성하세요.]
