### ISSUE TITLE
[Feature] Product Test Code 작성 및 Product 관련 API 수정

### ISSUE THREAD

**Issue by JuhyunPark1831** [PlanIt-Project/back-end#111]
### 요약
- Product Test Code 작성

### TODO 리스트
- [x] Product Test Code 작성
- [x] Product Entity toDto() 메서드 삭제
- [x] Product Selling Type 수정 API 구현
- [x] Product 삭제 불가능 -> 판매 중지로 변경
