### ISSUE TITLE
[Feature] 트레이너 스케쥴 테스트 코드 작성

### ISSUE THREAD

**Issue by thana973** [PlanIt-Project/back-end#127]
### 요약
테스트 코드 작성

### TODO 리스트
- [ ] 등록 기능 테스트 구현
- [ ] 수정 기능 테스트 구현
- [ ] 조회 기능 테스트 구현

### 상세 설명
테스트 코드 작성
