### ISSUE TITLE
[fix] reservation 예약 조회 옵션 추가 및 타임존 수정

### ISSUE THREAD

**Issue by moonjin-kim** [PlanIt-Project/back-end#128]
### 요약
[여기에 기능 요청의 간단한 요약을 작성하세요.]

### TODO 리스트
- [ ] reservation 예약 조회 기능 추가
- [ ] reservation 조회 테스트 코드 추가
- [ ] 서버 타입존 한국으로 변경

### 상세 설명
[여기에 기능 요청의 자세한 설명을 작성하세요.]

### ETC
[그 외의 사항을 작성하세요.]
