### ISSUE TITLE
[Feature] User 관련 기능 기초 API 구현

### ISSUE THREAD

**Issue by JuhyunPark1831** [PlanIt-Project/back-end#19]
### 요약
User 관련 기능 API 구현

### TODO 리스트
- [x] [회원 가입]
- [x] [회원 탈퇴]
- [x] [회원 정보 수정]
- [x] [회원 상세 조회]
- [x] [회원 목록 조회]
- [x] [직원 목록 조회]
- [x] [직원 권한 부여]

### 상세 설명
회원 가입: member 데이터 DB 저장
회원 탈퇴: member 데이터 삭제
회원 정보 수정: member 데이터 수정
회원 상세 조회: PK로 member 데이터 조회
회원 목록 조회: 모든 member 조회 (직원 제외)
직원 목록 조회: 모든 직원 조회
직원 권한 부여: member 데이터의 role 데이터 변경

### ETC
- 로그인, 로그아웃 기능은 추후 추후 JWT 인증 (security 관련)
