### ISSUE TITLE
[Feature]: 도메인 구분 및 Entity 코드 작성

### ISSUE THREAD

**Issue by JuhyunPark1831** [PlanIt-Project/back-end#3]
### 요약
[작성한 ERD에 따라서 도메인을 나누고, JPA를 사용하기 위한 Entity를 작성합니다.]

### TODO 리스트
- [x] [각 테이블 별 Entity 작성]
- [x] [JPA 연관 관계 설정]
- [x] [이미지 및 첨부 파일 등에 대한 처리 방식 선정 (현재는 파일 시스템에 저장 후 경로만 DB에 저장)] // Banner, Notice
- [x] [Banner, Notice의 게시일~종료일 처리 방식 (isExposure? startAt+endAt?) // Banner, Notice
- [x] [PT 스케줄링을 위한 트레이너의 출퇴근 시간 => 만약 요일별로 출퇴근 시간이 다르다면?] // Employee

### 상세 설명
[기본 도메인을 구분합니다. post, product, program, schedule, user로 구분하였고, JPA를 사용하기 위해 각각 관련되어있는 Entity를 도메인 내부 디렉토리에 작성합니다. 테이블 중 ENUM 타입의 컬럼이 존재하는 Entity를 위한 Enum 클래스도 작성합니다. Entity 작성 중에 발생한 더 확정 지어야할 부분, 생각하지 못한 이슈 등을 해결합니다.]
