### ISSUE TITLE
[Feature] 회원권 일시정지, 재시작 기능 추가

### ISSUE THREAD

**Issue by moonjin-kim** [PlanIt-Project/back-end#55]
### 요약
회원권 정보 수정 기능 추가

### TODO 리스트
- [ ] 회원권 일시정지 기능
- [ ] 회원권 재시작 기능
- [ ] 상품 period로 변경

### 상세 설명
[여기에 기능 요청의 자세한 설명을 작성하세요.]

### ETC
[그 외의 사항을 작성하세요.]
