### ISSUE TITLE
[Refactor] ResponseDto 등 코드 Refactoring

### ISSUE THREAD

**Issue by JuhyunPark1831** [PlanIt-Project/back-end#65]
### 요약
- 코드 Refactoring And 통일

### TODO 리스트
- [x] 개발 버전으로 개발에 용이하게 구현한 ResponseDto 들을 알맞게 반환하도록 수정
- [x] PK 컬럼명 통일: "id"
- [x] Employee Table에 trainerInfo 컬럼 추가
- [x] Entity의 toDto 메서드 Dto의 of로 변경 -> 객체 지향 원칙 (역할 분담)
- [x] Banner, Notice 삭제 API 미존재 -> 구현
