### ISSUE TITLE
[Fix] 상품의 판매 여부 상태가 없음

### ISSUE THREAD

**Issue by moonjin-kim** [PlanIt-Project/back-end#68]
### 요약
상품 판매 상태 기능 추가

### TODO 리스트
- [ ] 상품 판매 상태 기능 추가
- [ ] 판매 여부 수정 추가
- [ ] 상품 수정 시 기존 상품 판매 중지 상태로 변경 후 새 상품 추가
- [ ] 상품 상태에 따른 조회기능 추가

### 상세 설명
[여기에 기능 요청의 자세한 설명을 작성하세요.]

### ETC
[그 외의 사항을 작성하세요.]
