### ISSUE TITLE
[Feature] FileHandler 파일 반환 기능 구현 + Member 프로필 사진 관련 기능 구현

### ISSUE THREAD

**Issue by JuhyunPark1831** [PlanIt-Project/back-end#84]
### 요약
- 파일을 요청 받아서 저장하는 기능만 있는 FileHandler 모듈에 파일명을 요청 받아서 파일을 반환하는 기능 구현
- 회원/트레이너가 자신이 원하는 사진을 프로필 사진으로 등록하거나 수정 변경 삭제할 수 있는 기능 구현

### TODO 리스트
- [x] [파일 반환 기능 구현]
- [x] [회원 Entity profileImage 컬럼 추가
- [x] [프로필 사진 기능 구현]

### 상세 설명
- 프로필 사진 기능: 회원 가입 시에는 프로필 설정 불가(기본 프로필 이미지), 회원 가입 후 원하는 사진으로 변경 가능.
